[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    knolleary/PubSubClient@^2.8
    miguelbalboa/MFRC522@^1.4.10

build_flags = 
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_LOOP_STACK_SIZE=8192

upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
